// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef _UI_LIC66S_UI_H
#define _UI_LIC66S_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Intro.h"
#include "ui_HOME.h"
#include "ui_SCRGetLIC.h"
#include "ui_SCRSetLIC.h"
#include "ui_SCRconfigdevice.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * opaon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * opaoff_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveYIN_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveYOUT_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_settings_bg_png);    // assets/settings_bg.png
LV_IMG_DECLARE(ui_img_settings_corner_png);    // assets/settings_corner.png
LV_IMG_DECLARE(ui_img_icn_settings_png);    // assets/icn_settings.png
LV_IMG_DECLARE(ui_img_suync_png);    // assets/suync.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/Setting.png
LV_IMG_DECLARE(ui_img_key_png);    // assets/key.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/Clock.png
LV_IMG_DECLARE(ui_img_save_png);    // assets/save.png
LV_IMG_DECLARE(ui_img_icn_x_png);    // assets/icn_x.png

// FONTS
LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);
LV_FONT_DECLARE(ui_font_timesnewroman);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
