// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef _UI_COMP_DEVICEINFO1_H
#define _UI_COMP_DEVICEINFO1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT DeviceINFO1
#define UI_COMP_DEVICEINFO1_DEVICEINFO1 0
#define UI_COMP_DEVICEINFO1_DEVICEID2 1
#define UI_COMP_DEVICEINFO1_LOCALID2 2
#define UI_COMP_DEVICEINFO1_NUMDEVICE2 3
#define UI_COMP_DEVICEINFO1_MAC3 4
#define UI_COMP_DEVICEINFO1_MAC4 5
#define _UI_COMP_DEVICEINFO1_NUM 6
lv_obj_t * ui_DeviceINFO1_create(lv_obj_t * comp_parent,const char* ID ,const char* LID ,const char* NOD ,const char* MAC ,const char* TIME );
void ui_event_comp_DeviceINFO1_DeviceINFO1(lv_event_t * e);
lv_obj_t * add_Notification(lv_obj_t * comp_parent,const char* massager);
lv_obj_t * ui_Spinner_create(lv_obj_t * comp_parent);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
