// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"
#include "function.h"
void ui_event_comp_DeviceINFO1_DeviceINFO1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_DeviceINFO1 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(comp_DeviceINFO1[UI_COMP_DEVICEINFO1_DEVICEINFO1], LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_screen_change(&ui_SCRconfigdevice, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCRconfigdevice_screen_init);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(comp_DeviceINFO1[UI_COMP_DEVICEINFO1_DEVICEINFO1], LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Notification = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_Panel19, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Notification = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        // _ui_flag_modify(comp_Notification[0], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Panel19, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        lv_obj_del(comp_Notification[0]);

    }
}

// COMPONENT DeviceINFO1

lv_obj_t * ui_DeviceINFO1_create(lv_obj_t * comp_parent,const char* ID ,const char* LID ,const char* NOD ,const char* MAC ,const char* TIME )
{

    lv_obj_t * cui_DeviceINFO1;
    cui_DeviceINFO1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_DeviceINFO1, 710);
    lv_obj_set_height(cui_DeviceINFO1, 40);
    lv_obj_set_align(cui_DeviceINFO1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_DeviceINFO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_DeviceINFO1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_DeviceINFO1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_DeviceINFO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_DeviceINFO1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_DeviceINFO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_DeviceINFO1, lv_color_hex(0x00536D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_DeviceINFO1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_DeviceID2;
    cui_DeviceID2 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_DeviceID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_DeviceID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_DeviceID2, -300);
    lv_obj_set_y(cui_DeviceID2, 0);
    lv_obj_set_align(cui_DeviceID2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_DeviceID2, ID);
    lv_obj_set_style_text_color(cui_DeviceID2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_DeviceID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_DeviceID2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LocalID2;
    cui_LocalID2 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_LocalID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LocalID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LocalID2, -170);
    lv_obj_set_y(cui_LocalID2, 0);
    lv_obj_set_align(cui_LocalID2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LocalID2, LID);
    lv_obj_set_style_text_color(cui_LocalID2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LocalID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LocalID2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_NumDevice2;
    cui_NumDevice2 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_NumDevice2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_NumDevice2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_NumDevice2, -10);
    lv_obj_set_y(cui_NumDevice2, 0);
    lv_obj_set_align(cui_NumDevice2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_NumDevice2, NOD);
    lv_obj_set_style_text_color(cui_NumDevice2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_NumDevice2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_NumDevice2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MAC3;
    cui_MAC3 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_MAC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MAC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MAC3, 190);
    lv_obj_set_y(cui_MAC3, 0);
    lv_obj_set_align(cui_MAC3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MAC3, MAC);
    lv_obj_set_style_text_color(cui_MAC3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MAC3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MAC3, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MAC4;
    cui_MAC4 = lv_label_create(cui_DeviceINFO1);
    lv_obj_set_width(cui_MAC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MAC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MAC4, 310);
    lv_obj_set_y(cui_MAC4, 0);
    lv_obj_set_align(cui_MAC4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MAC4, TIME);
    lv_obj_set_style_text_color(cui_MAC4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MAC4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MAC4, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DEVICEINFO1_NUM);
    children[UI_COMP_DEVICEINFO1_DEVICEINFO1] = cui_DeviceINFO1;
    children[UI_COMP_DEVICEINFO1_DEVICEID2] = cui_DeviceID2;
    children[UI_COMP_DEVICEINFO1_LOCALID2] = cui_LocalID2;
    children[UI_COMP_DEVICEINFO1_NUMDEVICE2] = cui_NumDevice2;
    children[UI_COMP_DEVICEINFO1_MAC3] = cui_MAC3;
    children[UI_COMP_DEVICEINFO1_MAC4] = cui_MAC4;
    lv_obj_add_event_cb(cui_DeviceINFO1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_DeviceINFO1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_DeviceINFO1, ui_event_comp_DeviceINFO1_DeviceINFO1, LV_EVENT_ALL, children);
    ui_comp_DeviceINFO1_create_hook(cui_DeviceINFO1);
    return cui_DeviceINFO1;
}

lv_obj_t * ui_Spinner_create(lv_obj_t * comp_parent)
{
    lv_obj_t *ui_Spinner1 = lv_spinner_create(comp_parent, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 50);
    lv_obj_set_height(ui_Spinner1, 50);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x03A2FB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * 1);
    // children[0] = ui_Spinner1;
    // lv_obj_add_event_cb(ui_Spinner1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    // if (timer==NULL)
    // {
        timer =lv_timer_create(timer_cb, 5000, ui_Spinner1);
    // }
    
    
    return ui_Spinner1;
}
lv_obj_t * add_Notification(lv_obj_t * comp_parent,const char* massager)
{
    lv_obj_t * Panel_Notification;
    Panel_Notification = lv_obj_create(comp_parent);
    lv_obj_set_width(Panel_Notification, 400);
    lv_obj_set_height(Panel_Notification, 216);
    lv_obj_set_align(Panel_Notification, LV_ALIGN_CENTER);
    lv_obj_clear_flag(Panel_Notification, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(Panel_Notification, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(Panel_Notification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(Panel_Notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(Panel_Notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(Panel_Notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(Panel_Notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(Panel_Notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_t * Panel_tile = lv_obj_create(Panel_Notification);
    lv_obj_set_width(Panel_tile, 400);
    lv_obj_set_height(Panel_tile, 40);
    lv_obj_set_align(Panel_tile, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(Panel_tile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(Panel_tile, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(Panel_tile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(Panel_tile, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * Label_tile = lv_label_create(Panel_tile);
    lv_obj_set_width(Label_tile, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(Label_tile, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(Label_tile, LV_ALIGN_CENTER);
    lv_label_set_text(Label_tile, "Notification");
    lv_obj_set_style_text_font(Label_tile, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * Button_OK = lv_btn_create(Panel_Notification);
    lv_obj_set_width(Button_OK, 100);
    lv_obj_set_height(Button_OK, 28);
    lv_obj_set_x(Button_OK, -9);
    lv_obj_set_y(Button_OK, 63);
    lv_obj_set_align(Button_OK, LV_ALIGN_CENTER);
    lv_obj_add_flag(Button_OK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(Button_OK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(Button_OK, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(Button_OK, lv_color_hex(0x006A8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(Button_OK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * Label_button = lv_label_create(Button_OK);
    lv_obj_set_width(Label_button, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(Label_button, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(Label_button, LV_ALIGN_CENTER);
    lv_label_set_text(Label_button, "OK");
    lv_obj_set_style_text_font(Label_button, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * Panel_messager = lv_obj_create(Panel_Notification);
    lv_obj_set_width(Panel_messager, 292);
    lv_obj_set_height(Panel_messager, 77);
    lv_obj_set_align(Panel_messager, LV_ALIGN_CENTER);
    lv_obj_add_flag(Panel_messager, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(Panel_messager, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(Panel_messager, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(Panel_messager, lv_color_hex(0x868686), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(Panel_messager, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_t * Label_messager = lv_label_create(Panel_messager);
    lv_obj_set_width(Label_messager, 258);
    lv_obj_set_height(Label_messager, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(Label_messager, 2);
    lv_obj_set_y(Label_messager, -2);
    lv_obj_set_align(Label_messager, LV_ALIGN_TOP_MID);
    lv_label_set_text(Label_messager,
                      massager);
    lv_obj_set_style_text_font(Label_messager, &ui_font_timesnewroman, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * 2);

    children[0]=Panel_Notification;
    children[1]=Button_OK;
    lv_obj_add_event_cb(Panel_Notification, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(Panel_Notification, del_component_child_event_cb, LV_EVENT_DELETE, children);
    

    lv_obj_add_event_cb(Button_OK, ui_event_Button7, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(Panel_Notification, ui_event_Panel21, LV_EVENT_ALL, children);
    return Panel_Notification;
}