// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Scan_Licene(lv_event_t * e);
void Rescan_Licene(lv_event_t * e);
void Newscan_Licene(lv_event_t * e);
void Setlicene(lv_event_t * e);
void configdevice(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
