// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"
#include "function.h"
extern int next_page;

void Scan_Licene(lv_event_t * e)
{
	// Your code here
	
	if (timer!=NULL)
	{
		lv_timer_del(timer);
		timer=NULL;
	}
	if (ui_spinner1!=NULL)
	{
		lv_obj_del(ui_spinner1);
		ui_spinner1=NULL;
	}
	
	lv_obj_clean(ui_Groupdevice);
	get_id_lid_ui();
	ui_spinner1 = ui_Spinner_create(ui_Groupdevice);
	button=5;
	next_page=0;
}

void Rescan_Licene(lv_event_t * e)
{
	// Your code here
	lv_obj_clean(ui_Groupdevice);
	get_id_lid_ui();
	ui_spinner1 = ui_Spinner_create(ui_Groupdevice);
	button=4;
}

void Newscan_Licene(lv_event_t * e)
{
	// Your code here
	// lv_obj_clean(ui_Groupdevice);
	// get_id_lid_ui();
	// ui_spinner1 = ui_Spinner_create(ui_Groupdevice);
	// button=5;

	next_page++;

}

void Setlicene(lv_event_t * e)
{
	// Your code here

	get_lic_ui();
	if (ui_spinner!=NULL)
	{
		lv_obj_del(ui_spinner);
		ui_spinner=NULL;
	}
	
	ui_spinner = ui_Spinner_create(ui_SCRSetLIC);
	
	button=1;
}

void configdevice(lv_event_t * e)
{
	// Your code here
}