// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

lv_obj_t * ui_HOME = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Groupbutton1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Buttontop1 = NULL;
lv_obj_t * ui_Labelbutton1 = NULL;
lv_obj_t * ui_Groupbutton2 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Buttontop2 = NULL;
lv_obj_t * ui_Labelbutton2 = NULL;
lv_obj_t * ui_Groupbutton3 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Buttontop3 = NULL;
lv_obj_t * ui_Labelbutton3 = NULL;
lv_obj_t * ui_Groupbutton4 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Buttontop4 = NULL;
lv_obj_t * ui_Labelbutton4 = NULL;
lv_obj_t * ui_Groupbutton5 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Buttontop5 = NULL;
lv_obj_t * ui_Labelbutton5 = NULL;
lv_obj_t * ui_Groupbutton6 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Buttontop6 = NULL;
lv_obj_t * ui_Labelbutton6 = NULL;
// event funtions
void ui_event_HOME(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_delete(&ui_Intro);
    }
}

void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Panel2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Button1, 0);
        _ui_state_modify(ui_Buttontop1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Labelbutton1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Button1, 0);
        _ui_state_modify(ui_Labelbutton1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Buttontop1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_screen_change(&ui_SCRGetLIC, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCRGetLIC_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Button2, 0);
        _ui_state_modify(ui_Buttontop2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Labelbutton2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Button2, 0);
        _ui_state_modify(ui_Labelbutton2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Buttontop2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Button3, 0);
        _ui_state_modify(ui_Buttontop3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Labelbutton3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Button3, 0);
        _ui_state_modify(ui_Labelbutton3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Buttontop3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_screen_change(&ui_SCRSetLIC, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCRSetLIC_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Button4, 0);
        _ui_state_modify(ui_Buttontop4, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Labelbutton4, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Button4, 0);
        _ui_state_modify(ui_Labelbutton4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Buttontop4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Button5, 0);
        _ui_state_modify(ui_Buttontop5, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Labelbutton5, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Button5, 0);
        _ui_state_modify(ui_Labelbutton5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Buttontop5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Button6, 0);
        _ui_state_modify(ui_Buttontop6, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Labelbutton6, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Button6, 0);
        _ui_state_modify(ui_Labelbutton6, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Buttontop6, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// build funtions

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HOME, &ui_img_settings_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image1, &ui_img_settings_corner_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 353);
    lv_obj_set_y(ui_Image1, -212);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Image1);
    lv_obj_set_width(ui_Panel2, 30);
    lv_obj_set_height(ui_Panel2, 30);
    lv_obj_set_x(ui_Panel2, 20);
    lv_obj_set_y(ui_Panel2, 0);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel2, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel2, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Panel2, lv_color_hex(0x00BFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label1 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -336);
    lv_obj_set_y(ui_Label1, -206);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "LIC66S");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_HOME);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 650);
    lv_obj_set_height(ui_Container1, 343);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -33);
    lv_obj_set_align(ui_Container1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Groupbutton1 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Groupbutton1);
    lv_obj_set_width(ui_Groupbutton1, 120);
    lv_obj_set_height(ui_Groupbutton1, 154);
    lv_obj_set_align(ui_Groupbutton1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Groupbutton1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Groupbutton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Groupbutton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Groupbutton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Groupbutton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_obj_create(ui_Groupbutton1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 100);
    lv_obj_set_align(ui_Button1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x004356), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x00B6FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttontop1 = lv_obj_create(ui_Groupbutton1);
    lv_obj_set_width(ui_Buttontop1, 100);
    lv_obj_set_height(ui_Buttontop1, 100);
    lv_obj_set_align(ui_Buttontop1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Buttontop1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttontop1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttontop1, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttontop1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop1, &ui_img_suync_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttontop1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttontop1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop1, &ui_img_suync_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop1, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Labelbutton1 = lv_label_create(ui_Groupbutton1);
    lv_obj_set_width(ui_Labelbutton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelbutton1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelbutton1, 0);
    lv_obj_set_y(ui_Labelbutton1, 120);
    lv_obj_set_align(ui_Labelbutton1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Labelbutton1, "Get License");
    lv_obj_set_style_text_color(ui_Labelbutton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelbutton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelbutton1, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Labelbutton1, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Labelbutton1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Groupbutton2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Groupbutton2);
    lv_obj_set_width(ui_Groupbutton2, 120);
    lv_obj_set_height(ui_Groupbutton2, 154);
    lv_obj_set_align(ui_Groupbutton2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Groupbutton2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Groupbutton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Groupbutton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Groupbutton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Groupbutton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_obj_create(ui_Groupbutton2);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 100);
    lv_obj_set_align(ui_Button2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x004356), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x00B6FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttontop2 = lv_obj_create(ui_Groupbutton2);
    lv_obj_set_width(ui_Buttontop2, 100);
    lv_obj_set_height(ui_Buttontop2, 100);
    lv_obj_set_align(ui_Buttontop2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Buttontop2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttontop2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttontop2, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttontop2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop2, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttontop2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttontop2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop2, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop2, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Labelbutton2 = lv_label_create(ui_Groupbutton2);
    lv_obj_set_width(ui_Labelbutton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelbutton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelbutton2, 0);
    lv_obj_set_y(ui_Labelbutton2, 120);
    lv_obj_set_align(ui_Labelbutton2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Labelbutton2, "Setting");
    lv_obj_set_style_text_color(ui_Labelbutton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelbutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelbutton2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Labelbutton2, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Labelbutton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Groupbutton3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Groupbutton3);
    lv_obj_set_width(ui_Groupbutton3, 120);
    lv_obj_set_height(ui_Groupbutton3, 154);
    lv_obj_set_align(ui_Groupbutton3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Groupbutton3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Groupbutton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Groupbutton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Groupbutton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Groupbutton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_obj_create(ui_Groupbutton3);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 100);
    lv_obj_set_align(ui_Button3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x004356), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x00B6FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttontop3 = lv_obj_create(ui_Groupbutton3);
    lv_obj_set_width(ui_Buttontop3, 100);
    lv_obj_set_height(ui_Buttontop3, 100);
    lv_obj_set_align(ui_Buttontop3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Buttontop3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttontop3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttontop3, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttontop3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop3, &ui_img_key_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttontop3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttontop3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop3, &ui_img_key_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop3, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Labelbutton3 = lv_label_create(ui_Groupbutton3);
    lv_obj_set_width(ui_Labelbutton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelbutton3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelbutton3, 0);
    lv_obj_set_y(ui_Labelbutton3, 120);
    lv_obj_set_align(ui_Labelbutton3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Labelbutton3, "Set License");
    lv_obj_set_style_text_color(ui_Labelbutton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelbutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelbutton3, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Labelbutton3, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Labelbutton3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Groupbutton4 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Groupbutton4);
    lv_obj_set_width(ui_Groupbutton4, 120);
    lv_obj_set_height(ui_Groupbutton4, 154);
    lv_obj_set_align(ui_Groupbutton4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Groupbutton4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Groupbutton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Groupbutton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Groupbutton4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Groupbutton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_obj_create(ui_Groupbutton4);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 100);
    lv_obj_set_align(ui_Button4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x004356), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x00B6FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttontop4 = lv_obj_create(ui_Groupbutton4);
    lv_obj_set_width(ui_Buttontop4, 100);
    lv_obj_set_height(ui_Buttontop4, 100);
    lv_obj_set_align(ui_Buttontop4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Buttontop4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttontop4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttontop4, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttontop4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop4, &ui_img_cloud_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttontop4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttontop4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop4, &ui_img_cloud_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop4, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Labelbutton4 = lv_label_create(ui_Groupbutton4);
    lv_obj_set_width(ui_Labelbutton4, 110);
    lv_obj_set_height(ui_Labelbutton4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelbutton4, 0);
    lv_obj_set_y(ui_Labelbutton4, 120);
    lv_obj_set_align(ui_Labelbutton4, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Labelbutton4, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Labelbutton4, "Dowload License");
    lv_label_set_recolor(ui_Labelbutton4, "true");
    lv_obj_set_style_text_color(ui_Labelbutton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelbutton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelbutton4, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Labelbutton4, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Labelbutton4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Groupbutton5 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Groupbutton5);
    lv_obj_set_width(ui_Groupbutton5, 120);
    lv_obj_set_height(ui_Groupbutton5, 154);
    lv_obj_set_align(ui_Groupbutton5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Groupbutton5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Groupbutton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Groupbutton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Groupbutton5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Groupbutton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_obj_create(ui_Groupbutton5);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 100);
    lv_obj_set_align(ui_Button5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x004356), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x00B6FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttontop5 = lv_obj_create(ui_Groupbutton5);
    lv_obj_set_width(ui_Buttontop5, 100);
    lv_obj_set_height(ui_Buttontop5, 100);
    lv_obj_set_align(ui_Buttontop5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Buttontop5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttontop5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttontop5, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttontop5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop5, &ui_img_clock_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttontop5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttontop5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop5, &ui_img_clock_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop5, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Labelbutton5 = lv_label_create(ui_Groupbutton5);
    lv_obj_set_width(ui_Labelbutton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelbutton5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelbutton5, 0);
    lv_obj_set_y(ui_Labelbutton5, 120);
    lv_obj_set_align(ui_Labelbutton5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Labelbutton5, "Get Time");
    lv_obj_set_style_text_color(ui_Labelbutton5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelbutton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelbutton5, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Labelbutton5, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Labelbutton5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Groupbutton6 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Groupbutton6);
    lv_obj_set_width(ui_Groupbutton6, 120);
    lv_obj_set_height(ui_Groupbutton6, 154);
    lv_obj_set_align(ui_Groupbutton6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Groupbutton6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Groupbutton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Groupbutton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Groupbutton6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Groupbutton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_obj_create(ui_Groupbutton6);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 100);
    lv_obj_set_align(ui_Button6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x004356), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x00B6FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttontop6 = lv_obj_create(ui_Groupbutton6);
    lv_obj_set_width(ui_Buttontop6, 100);
    lv_obj_set_height(ui_Buttontop6, 100);
    lv_obj_set_align(ui_Buttontop6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Buttontop6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttontop6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttontop6, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttontop6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop6, &ui_img_save_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttontop6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttontop6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Buttontop6, &ui_img_save_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Buttontop6, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Buttontop6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Labelbutton6 = lv_label_create(ui_Groupbutton6);
    lv_obj_set_width(ui_Labelbutton6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelbutton6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelbutton6, 0);
    lv_obj_set_y(ui_Labelbutton6, 120);
    lv_obj_set_align(ui_Labelbutton6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Labelbutton6, "List License");
    lv_obj_set_style_text_color(ui_Labelbutton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelbutton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelbutton6, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Labelbutton6, lv_color_hex(0x009CFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Labelbutton6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HOME, ui_event_HOME, LV_EVENT_ALL, NULL);

}

void ui_HOME_screen_destroy(void)
{
    if(ui_HOME) lv_obj_del(ui_HOME);

    // NULL screen variables
    ui_HOME = NULL;
    ui_Image1 = NULL;
    ui_Panel2 = NULL;
    ui_Label1 = NULL;
    ui_Container1 = NULL;
    ui_Groupbutton1 = NULL;
    ui_Button1 = NULL;
    ui_Buttontop1 = NULL;
    ui_Labelbutton1 = NULL;
    ui_Groupbutton2 = NULL;
    ui_Button2 = NULL;
    ui_Buttontop2 = NULL;
    ui_Labelbutton2 = NULL;
    ui_Groupbutton3 = NULL;
    ui_Button3 = NULL;
    ui_Buttontop3 = NULL;
    ui_Labelbutton3 = NULL;
    ui_Groupbutton4 = NULL;
    ui_Button4 = NULL;
    ui_Buttontop4 = NULL;
    ui_Labelbutton4 = NULL;
    ui_Groupbutton5 = NULL;
    ui_Button5 = NULL;
    ui_Buttontop5 = NULL;
    ui_Labelbutton5 = NULL;
    ui_Groupbutton6 = NULL;
    ui_Button6 = NULL;
    ui_Buttontop6 = NULL;
    ui_Labelbutton6 = NULL;

}
