// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HOME
extern void ui_HOME_screen_init(void);
extern void ui_HOME_screen_destroy(void);
extern void ui_event_HOME(lv_event_t * e);
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_Image1;
extern void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Groupbutton1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Buttontop1;
extern lv_obj_t * ui_Labelbutton1;
extern lv_obj_t * ui_Groupbutton2;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Buttontop2;
extern lv_obj_t * ui_Labelbutton2;
extern lv_obj_t * ui_Groupbutton3;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Buttontop3;
extern lv_obj_t * ui_Labelbutton3;
extern lv_obj_t * ui_Groupbutton4;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Buttontop4;
extern lv_obj_t * ui_Labelbutton4;
extern lv_obj_t * ui_Groupbutton5;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Buttontop5;
extern lv_obj_t * ui_Labelbutton5;
extern lv_obj_t * ui_Groupbutton6;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Buttontop6;
extern lv_obj_t * ui_Labelbutton6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

