// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef UI_INTRO_H
#define UI_INTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Intro
extern void ui_Intro_screen_init(void);
extern void ui_Intro_screen_destroy(void);
extern void ui_event_Intro(lv_event_t * e);
extern lv_obj_t * ui_Intro;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container5;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label6;
extern void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

