// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef UI_SCRCONFIGDEVICE_H
#define UI_SCRCONFIGDEVICE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCRconfigdevice
extern void ui_SCRconfigdevice_screen_init(void);
extern void ui_SCRconfigdevice_screen_destroy(void);
extern lv_obj_t * ui_SCRconfigdevice;
extern lv_obj_t * ui_Image5;
extern void ui_event_Panel24(lv_event_t * e);
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Container15;
extern void ui_event_Panel28(lv_event_t * e);
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Container17;
extern void ui_event_Panel30(lv_event_t * e);
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_TextArea8;
extern void ui_event_Panel31(lv_event_t * e);
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_TextArea9;
extern void ui_event_Panel32(lv_event_t * e);
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_TextArea10;
extern void ui_event_Keyboard4(lv_event_t * e);
extern lv_obj_t * ui_Keyboard4;
extern void ui_event_Panel34(lv_event_t * e);
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Label31;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

