// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

lv_obj_t * ui_SCRconfigdevice = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Panel24 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Panel28 = NULL;
lv_obj_t * ui_Panel29 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Panel30 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_TextArea8 = NULL;
lv_obj_t * ui_Panel31 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_TextArea9 = NULL;
lv_obj_t * ui_Panel32 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_TextArea10 = NULL;
lv_obj_t * ui_Keyboard4 = NULL;
lv_obj_t * ui_Panel34 = NULL;
lv_obj_t * ui_Panel35 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Panel36 = NULL;
lv_obj_t * ui_Label33 = NULL;
// event funtions
void ui_event_Panel24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel24, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Panel24, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_screen_change(&ui_SCRGetLIC, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCRGetLIC_screen_init);
    }
}

void ui_event_Panel28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Panel28, 0);
        _ui_state_modify(ui_Panel29, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Panel28, 0);
        _ui_state_modify(ui_Panel29, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        configdevice(e);
    }
}

void ui_event_Panel30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel31, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard4,  ui_TextArea8);
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel30, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Panel32, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel30, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard4,  ui_TextArea9);
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel31, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Panel32, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel30, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard4,  ui_TextArea10);
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel32, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Panel31, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Keyboard4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Panel32, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel31, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Panel30, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_Panel30, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel34, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_SCRconfigdevice_screen_init(void)
{
    ui_SCRconfigdevice = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCRconfigdevice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_SCRconfigdevice, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_SCRconfigdevice);
    lv_obj_set_style_bg_color(ui_SCRconfigdevice, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SCRconfigdevice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SCRconfigdevice, &ui_img_settings_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_SCRconfigdevice);
    lv_img_set_src(ui_Image5, &ui_img_settings_corner_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 353);
    lv_obj_set_y(ui_Image5, -212);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel24 = lv_obj_create(ui_Image5);
    lv_obj_set_width(ui_Panel24, 30);
    lv_obj_set_height(ui_Panel24, 30);
    lv_obj_set_x(ui_Panel24, 20);
    lv_obj_set_y(ui_Panel24, 0);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel24, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel24, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Panel24, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label24 = lv_label_create(ui_SCRconfigdevice);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -336);
    lv_obj_set_y(ui_Label24, -206);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "LIC66S");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_SCRconfigdevice);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -269);
    lv_obj_set_y(ui_Label25, -134);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Config device");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_SCRconfigdevice);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 336);
    lv_obj_set_height(ui_Container14, 51);
    lv_obj_set_x(ui_Container14, -157);
    lv_obj_set_y(ui_Container14, -68);
    lv_obj_set_align(ui_Container14, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container14, -10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container14);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 120);
    lv_obj_set_height(ui_Container15, 50);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel28 = lv_obj_create(ui_Container15);
    lv_obj_set_width(ui_Panel28, 100);
    lv_obj_set_height(ui_Panel28, 30);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel28, lv_color_hex(0x00ACFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel28, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel28, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_Container15);
    lv_obj_set_width(ui_Panel29, 100);
    lv_obj_set_height(ui_Panel29, 30);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel29, lv_color_hex(0x0083EF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel29, lv_color_hex(0x00BCDD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label26 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Set");

    ui_Container17 = lv_obj_create(ui_SCRconfigdevice);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 325);
    lv_obj_set_height(ui_Container17, 206);
    lv_obj_set_x(ui_Container17, 80);
    lv_obj_set_y(ui_Container17, 18);
    lv_obj_set_align(ui_Container17, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Container17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container17, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container17, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel30 = lv_obj_create(ui_Container17);
    lv_obj_set_width(ui_Panel30, 320);
    lv_obj_set_height(ui_Panel30, 35);
    lv_obj_set_x(ui_Panel30, 482);
    lv_obj_set_y(ui_Panel30, -138);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel30, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel30, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label27 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label27, "Device ID:");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea8 = lv_textarea_create(ui_Panel30);
    lv_obj_set_width(ui_TextArea8, 200);
    lv_obj_set_height(ui_TextArea8, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea8, 140);
    lv_obj_set_y(ui_TextArea8, 0);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea8, 5);
    lv_textarea_set_placeholder_text(ui_TextArea8, "..................");
    lv_textarea_set_one_line(ui_TextArea8, true);
    lv_obj_clear_flag(ui_TextArea8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea8, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel31 = lv_obj_create(ui_Container17);
    lv_obj_set_width(ui_Panel31, 320);
    lv_obj_set_height(ui_Panel31, 35);
    lv_obj_set_x(ui_Panel31, 482);
    lv_obj_set_y(ui_Panel31, -138);
    lv_obj_set_align(ui_Panel31, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel31, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel31, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel31, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label28 = lv_label_create(ui_Panel31);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label28, "Local ID:");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea9 = lv_textarea_create(ui_Panel31);
    lv_obj_set_width(ui_TextArea9, 200);
    lv_obj_set_height(ui_TextArea9, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea9, 140);
    lv_obj_set_y(ui_TextArea9, 0);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea9, 5);
    lv_textarea_set_placeholder_text(ui_TextArea9, "..................");
    lv_textarea_set_one_line(ui_TextArea9, true);
    lv_obj_clear_flag(ui_TextArea9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea9, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel32 = lv_obj_create(ui_Container17);
    lv_obj_set_width(ui_Panel32, 320);
    lv_obj_set_height(ui_Panel32, 35);
    lv_obj_set_x(ui_Panel32, 482);
    lv_obj_set_y(ui_Panel32, -138);
    lv_obj_set_align(ui_Panel32, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel32, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel32, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel32, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label29 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label29, "Number of device:");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea10 = lv_textarea_create(ui_Panel32);
    lv_obj_set_width(ui_TextArea10, 200);
    lv_obj_set_height(ui_TextArea10, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea10, 140);
    lv_obj_set_y(ui_TextArea10, 0);
    lv_obj_set_align(ui_TextArea10, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea10, 5);
    lv_textarea_set_placeholder_text(ui_TextArea10, "..................");
    lv_textarea_set_one_line(ui_TextArea10, true);
    lv_obj_clear_flag(ui_TextArea10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea10, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard4 = lv_keyboard_create(ui_SCRconfigdevice);
    lv_keyboard_set_mode(ui_Keyboard4, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard4, 345);
    lv_obj_set_height(ui_Keyboard4, 270);
    lv_obj_set_x(ui_Keyboard4, 216);
    lv_obj_set_y(ui_Keyboard4, -19);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard4, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard4, lv_color_hex(0x002835), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard4, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Keyboard4, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard4, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard4, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard4, &lv_font_montserrat_30, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Panel34 = lv_obj_create(ui_SCRconfigdevice);
    lv_obj_set_width(ui_Panel34, 400);
    lv_obj_set_height(ui_Panel34, 216);
    lv_obj_set_align(ui_Panel34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel34, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel34, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel35 = lv_obj_create(ui_Panel34);
    lv_obj_set_width(ui_Panel35, 400);
    lv_obj_set_height(ui_Panel35, 40);
    lv_obj_set_align(ui_Panel35, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel35, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel35);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Notification");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_Panel34);
    lv_obj_set_width(ui_Button8, 100);
    lv_obj_set_height(ui_Button8, 28);
    lv_obj_set_x(ui_Button8, -9);
    lv_obj_set_y(ui_Button8, 63);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x006A8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "OK");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel36 = lv_obj_create(ui_Panel34);
    lv_obj_set_width(ui_Panel36, 292);
    lv_obj_set_height(ui_Panel36, 77);
    lv_obj_set_align(ui_Panel36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel36, lv_color_hex(0x868686), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel36, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Panel36);
    lv_obj_set_width(ui_Label33, 258);
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_Label33, 2);
    lv_obj_set_y(ui_Label33, -2);
    lv_obj_set_align(ui_Label33, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label33,
                      "kghkkghfgfhfhfhfghfghfghghfghghfghfhfghgkjkjjjjjjjjjjjjjjjjjjjjjjjkjkjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_timesnewroman, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel24, ui_event_Panel24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel28, ui_event_Panel28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel30, ui_event_Panel30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel31, ui_event_Panel31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel32, ui_event_Panel32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard4, ui_event_Keyboard4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel34, ui_event_Panel34, LV_EVENT_ALL, NULL);

}

void ui_SCRconfigdevice_screen_destroy(void)
{
    if(ui_SCRconfigdevice) lv_obj_del(ui_SCRconfigdevice);

    // NULL screen variables
    ui_SCRconfigdevice = NULL;
    ui_Image5 = NULL;
    ui_Panel24 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Container14 = NULL;
    ui_Container15 = NULL;
    ui_Panel28 = NULL;
    ui_Panel29 = NULL;
    ui_Label26 = NULL;
    ui_Container17 = NULL;
    ui_Panel30 = NULL;
    ui_Label27 = NULL;
    ui_TextArea8 = NULL;
    ui_Panel31 = NULL;
    ui_Label28 = NULL;
    ui_TextArea9 = NULL;
    ui_Panel32 = NULL;
    ui_Label29 = NULL;
    ui_TextArea10 = NULL;
    ui_Keyboard4 = NULL;
    ui_Panel34 = NULL;
    ui_Panel35 = NULL;
    ui_Label31 = NULL;
    ui_Button8 = NULL;
    ui_Label32 = NULL;
    ui_Panel36 = NULL;
    ui_Label33 = NULL;

}
