// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef UI_SCRGETLIC_H
#define UI_SCRGETLIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCRGetLIC
extern void ui_SCRGetLIC_screen_init(void);
extern void ui_SCRGetLIC_screen_destroy(void);
extern lv_obj_t * ui_SCRGetLIC;
extern lv_obj_t * ui_Image2;
extern void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Container7;
extern void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TextArea2;
extern void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container9;
extern void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container10;
extern void ui_event_Panel12(lv_event_t * e);
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container11;
extern void ui_event_Panel14(lv_event_t * e);
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Groupdevice;
extern lv_obj_t * ui_DeviceINFO1;
extern void ui_event_Keyboard3(lv_event_t * e);
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

