// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#ifndef UI_SCRSETLIC_H
#define UI_SCRSETLIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCRSetLIC
extern void ui_SCRSetLIC_screen_init(void);
extern void ui_SCRSetLIC_screen_destroy(void);
extern lv_obj_t * ui_SCRSetLIC;
extern lv_obj_t * ui_Image3;
extern void ui_event_Panel17(lv_event_t * e);
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Container16;
extern void ui_event_Panel25(lv_event_t * e);
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Container6;
extern void ui_event_Panel19(lv_event_t * e);
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_TextArea4;
extern void ui_event_Panel20(lv_event_t * e);
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_TextArea5;
extern void ui_event_Panel18(lv_event_t * e);
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_TextArea6;
extern void ui_event_Panel27(lv_event_t * e);
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_Image4;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// extern void ui_event_Panel21(lv_event_t * e);
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Label18;
// extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_spinner;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

