// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UI_LIC66S

#include "ui.h"

lv_obj_t * ui_SCRGetLIC = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Groupdevice = NULL;
lv_obj_t * ui_DeviceINFO1 = NULL;
lv_obj_t * ui_Keyboard3 = NULL;
lv_obj_t * ui_spinner1 = NULL;
// event funtions
void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Panel1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HOME_screen_init);
    }
}

void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel9, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea2);
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel8, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_Panel9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Panel8, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea3);
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Panel9, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_Panel10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Panel10, 0);
        _ui_state_modify(ui_Panel11, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Panel10, 0);
        _ui_state_modify(ui_Panel11, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        Scan_Licene(e);
    }
}

void ui_event_Panel12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Panel12, 0);
        _ui_state_modify(ui_Panel13, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Panel12, 0);
        _ui_state_modify(ui_Panel13, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        Rescan_Licene(e);
    }
}

void ui_event_Panel14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        opaon_Animation(ui_Panel14, 0);
        _ui_state_modify(ui_Panel15, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        opaoff_Animation(ui_Panel14, 0);
        _ui_state_modify(ui_Panel15, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        Newscan_Licene(e);
    }
}

void ui_event_Keyboard3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_SCRGetLIC_screen_init(void)
{
    ui_SCRGetLIC = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCRGetLIC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_add_event_cb(ui_SCRGetLIC, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_SCRGetLIC);
    lv_obj_set_style_bg_color(ui_SCRGetLIC, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SCRGetLIC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SCRGetLIC, &ui_img_settings_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_SCRGetLIC);
    lv_img_set_src(ui_Image2, &ui_img_settings_corner_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 353);
    lv_obj_set_y(ui_Image2, -212);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Image2);
    lv_obj_set_width(ui_Panel1, 30);
    lv_obj_set_height(ui_Panel1, 30);
    lv_obj_set_x(ui_Panel1, 20);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel1, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel1, &ui_img_icn_x_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Panel1, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label2 = lv_label_create(ui_SCRGetLIC);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -336);
    lv_obj_set_y(ui_Label2, -206);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "LIC66S");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_SCRGetLIC);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -281);
    lv_obj_set_y(ui_Label7, -151);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "LIST DEVICE: ");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_SCRGetLIC);
    lv_obj_set_width(ui_Panel16, 780);
    lv_obj_set_height(ui_Panel16, 45);
    lv_obj_set_x(ui_Panel16, 0);
    lv_obj_set_y(ui_Panel16, -110);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel16, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Panel16);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 484);
    lv_obj_set_height(ui_Container7, 50);
    lv_obj_set_x(ui_Container7, -160);
    lv_obj_set_y(ui_Container7, 0);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_Panel8, 210);
    lv_obj_set_height(ui_Panel8, 35);
    lv_obj_set_x(ui_Panel8, 482);
    lv_obj_set_y(ui_Panel8, -138);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel8, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label8 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label8, "Device ID:");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Panel8);
    lv_obj_set_width(ui_TextArea2, 82);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea2, 60);
    lv_obj_set_y(ui_TextArea2, 0);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea2, 5);
    lv_textarea_set_placeholder_text(ui_TextArea2, "..................");
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_obj_clear_flag(ui_TextArea2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_Panel9, 210);
    lv_obj_set_height(ui_Panel9, 35);
    lv_obj_set_x(ui_Panel9, 482);
    lv_obj_set_y(ui_Panel9, -138);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel9, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x00749A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label9 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label9, "Local ID:");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_Panel9);
    lv_obj_set_width(ui_TextArea3, 82);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea3, 46);
    lv_obj_set_y(ui_TextArea3, 0);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea3, 5);
    lv_textarea_set_placeholder_text(ui_TextArea3, "..................");
    lv_textarea_set_one_line(ui_TextArea3, true);
    lv_obj_clear_flag(ui_TextArea3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea3, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Panel16);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 340);
    lv_obj_set_height(ui_Container8, 50);
    lv_obj_set_x(ui_Container8, 420);
    lv_obj_set_y(ui_Container8, 0);
    lv_obj_set_align(ui_Container8, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container8, -10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 120);
    lv_obj_set_height(ui_Container9, 50);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel10 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Panel10, 100);
    lv_obj_set_height(ui_Panel10, 30);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel10, lv_color_hex(0x00ACFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel10, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Panel11, 100);
    lv_obj_set_height(ui_Panel11, 30);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x0083EF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel11, lv_color_hex(0x00BCDD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label10 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Scan");

    ui_Container10 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 120);
    lv_obj_set_height(ui_Container10, 50);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_Panel12, 100);
    lv_obj_set_height(ui_Panel12, 30);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel12, lv_color_hex(0x00ACFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel12, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_Panel13, 100);
    lv_obj_set_height(ui_Panel13, 30);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x0083EF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel13, lv_color_hex(0x00BCDD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label11 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Rescan");

    ui_Container11 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 120);
    lv_obj_set_height(ui_Container11, 50);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_Panel14, 100);
    lv_obj_set_height(ui_Panel14, 30);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel14, lv_color_hex(0x00ACFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel14, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel14, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_Panel15, 100);
    lv_obj_set_height(ui_Panel15, 30);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x0083EF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel15, lv_color_hex(0x00BCDD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label12 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Next Page");

    ui_Container12 = lv_obj_create(ui_SCRGetLIC);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 710);
    lv_obj_set_height(ui_Container12, 40);
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, -65);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container12, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 10);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label13,
                      "Device ID			  	Local ID	 	     Number device                      Mac	              Time");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Groupdevice = lv_obj_create(ui_SCRGetLIC);
    lv_obj_set_width(ui_Groupdevice, 710);
    lv_obj_set_height(ui_Groupdevice, 260);
    lv_obj_set_x(ui_Groupdevice, 0);
    lv_obj_set_y(ui_Groupdevice, -20);
    lv_obj_set_align(ui_Groupdevice, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Groupdevice, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Groupdevice, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Groupdevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Groupdevice, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Groupdevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Groupdevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Groupdevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Groupdevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Groupdevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Groupdevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_DeviceINFO1 = ui_DeviceINFO1_create(ui_Groupdevice);
    // lv_obj_set_x(ui_DeviceINFO1, 0);
    // lv_obj_set_y(ui_DeviceINFO1, 0);

    ui_Keyboard3 = lv_keyboard_create(ui_SCRGetLIC);
    lv_keyboard_set_mode(ui_Keyboard3, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard3, 345);
    lv_obj_set_height(ui_Keyboard3, 220);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard3, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard3, lv_color_hex(0x002835), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard3, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Keyboard3, LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard3, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard3, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard3, &lv_font_montserrat_30, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel9, ui_event_Panel9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel10, ui_event_Panel10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel12, ui_event_Panel12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel14, ui_event_Panel14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard3, ui_event_Keyboard3, LV_EVENT_ALL, NULL);

}

void ui_SCRGetLIC_screen_destroy(void)
{
    if(ui_SCRGetLIC) lv_obj_del(ui_SCRGetLIC);

    // NULL screen variables
    ui_SCRGetLIC = NULL;
    ui_Image2 = NULL;
    ui_Panel1 = NULL;
    ui_Label2 = NULL;
    ui_Label7 = NULL;
    ui_Panel16 = NULL;
    ui_Container7 = NULL;
    ui_Panel8 = NULL;
    ui_Label8 = NULL;
    ui_TextArea2 = NULL;
    ui_Panel9 = NULL;
    ui_Label9 = NULL;
    ui_TextArea3 = NULL;
    ui_Container8 = NULL;
    ui_Container9 = NULL;
    ui_Panel10 = NULL;
    ui_Panel11 = NULL;
    ui_Label10 = NULL;
    ui_Container10 = NULL;
    ui_Panel12 = NULL;
    ui_Panel13 = NULL;
    ui_Label11 = NULL;
    ui_Container11 = NULL;
    ui_Panel14 = NULL;
    ui_Panel15 = NULL;
    ui_Label12 = NULL;
    ui_Container12 = NULL;
    ui_Label13 = NULL;
    ui_Groupdevice = NULL;
    ui_DeviceINFO1 = NULL;
    ui_Keyboard3 = NULL;

}
